In [21]:
import pandas as pd
import numpy as np

In [22]:
np.random.seed(1)#we can fix the random sequence
age = np.random.randint(10,100,15)
print(age)

[47 22 82 19 85 15 89 74 26 11 86 81 16 35 60]

In [23]:
s = pd.Series(age)

In [24]:
s.head()

0    47
1    22
2    82
3    19
4    85
dtype: int64

In [25]:
s.tail(2)

13    35
14    60
dtype: int64

In [8]:
s[0]

82

In [9]:
s[0:5]

0    82
1    13
2    81
3    86
4    21
dtype: int32

In [21]:
data = {
    "scores" : np.random.randint(20,120,8),
    "names" : np.array(['Sachin','Dhoni','Kohli','Yuvraj','Raina','Rohit','Rishabh','Jadeja']),
    "catches" : np.random.randint(1,6,8),
    "average" : np.random.randint(40,55,8)
}

In [22]:
data

{'scores': array([ 40,  38, 104,  31,  48,  49,  34,  70]),
 'names': array(['Sachin', 'Dhoni', 'Kohli', 'Yuvraj', 'Raina', 'Rohit', 'Rishabh',
        'Jadeja'], dtype='<U7'),
 'catches': array([5, 2, 2, 1, 2, 2, 2, 2]),
 'average': array([40, 52, 41, 48, 48, 53, 43, 50])}

In [45]:
df = pd.DataFrame(data)

In [46]:
df[(df["average"]>40) | (df["catches"]>=2)]

   scores    names  catches  average
0      40   Sachin        5       40
1      38    Dhoni        2       52
2     104    Kohli        2       41
3      31   Yuvraj        1       48
4      48    Raina        2       48
5      49    Rohit        2       53
6      34  Rishabh        2       43
7      70   Jadeja        2       50

In [19]:
df.head()

   scores   names  catches  average
0      23  Sachin        2       54
1      27   Dhoni        4       48
2      71   Kohli        2       49
3     108  Yuvraj        3       43
4      87   Raina        5       48

In [21]:
df[df['catches'] >= 4]

   scores  names  catches  average
1      27  Dhoni        4       48
4      87  Raina        5       48
5      92  Rohit        4       48

In [22]:
df[df['catches'] >= 4][['names','average']]

   names  average
1  Dhoni       48
4  Raina       48
5  Rohit       48