In [1]:
#ipynb - Interactive PYthon NoteBook
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
len(x)

5

In [10]:
p = [1,2,3,4,5]
res = list(map(lambda a : a**2,p))

In [11]:
res

[1, 4, 9, 16, 25]

In [12]:
x

array([1, 2, 3, 4, 5])

In [14]:
x*5

array([ 5, 10, 15, 20, 25])

In [21]:
x = np.array([200,0,-1,-2,4,5,6,9,2])

In [22]:
min(x)

np.int64(-2)

In [23]:
max(x)

np.int64(200)

In [24]:
sum(x)

np.int64(223)

In [25]:
x

array([200,   0,  -1,  -2,   4,   5,   6,   9,   2])

In [26]:
x.argmin()

np.int64(3)

In [27]:
x.argmax()

np.int64(0)

In [31]:
x.argsort()

array([3, 2, 1, 8, 4, 5, 6, 7, 0])

In [34]:
sorted(x,reverse = True)

[np.int64(200),
 np.int64(9),
 np.int64(6),
 np.int64(5),
 np.int64(4),
 np.int64(2),
 np.int64(0),
 np.int64(-1),
 np.int64(-2)]

In [44]:
x = np.random.randint(1,11)
x

3

In [45]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
x.shape

(3, 3)

In [48]:
x.ndim

2

In [49]:
a = np.array([1,2,34])

In [50]:
a.shape

(3,)

In [51]:
a.ndim

1

In [52]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
x.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
x.reshape(9,).T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import pandas as pd

In [14]:
# data = {
#     'rollNo' :[1,2,3,4,5],
#     'name' : ["amit","suresh","yash","neha","aman"],
#     'marks' : [100,90,60,70,40]
# }

data = [['roll','name','marks'],
        [1,"amit",100],
        [2,"suresh",90],
        [3,"yash",60],
        [4,"neha",70],
        [5,"aman",40]]

In [10]:
sr1=pd.Series(data['name'])

In [11]:
sr1[0:3]

0      amit
1    suresh
2      yash
dtype: object

In [22]:
df = pd.DataFrame(index = ["a101","a102","a103","a104","a105"],data = data[1:],columns=data[0])

In [23]:
df

      roll    name  marks
a101     1    amit    100
a102     2  suresh     90
a103     3    yash     60
a104     4    neha     70
a105     5    aman     40

In [24]:
df = pd.DataFrame({
    'rollNo' :[1,2,3,4,5],
    'name' : ["amit","suresh","yash","neha","aman"],
    'marks' : [100,90,60,70,40]})

In [25]:
df

   rollNo    name  marks
0       1    amit    100
1       2  suresh     90
2       3    yash     60
3       4    neha     70
4       5    aman     40

In [26]:
#slicing and indexing

In [28]:
df['rollNo']

0    1
1    2
2    3
3    4
4    5
Name: rollNo, dtype: int64

In [35]:
df

   rollNo    name  marks
0       1    amit    100
1       2  suresh     90
2       3    yash     60
3       4    neha     70
4       5    aman     40

In [39]:
df.iloc[0:3]["rollNo"]

0    1
1    2
2    3
Name: rollNo, dtype: int64

In [42]:
df

   rollNo    name  marks
0       1    amit    100
1       2  suresh     90
2       3    yash     60
3       4    neha     70
4       5    aman     40

In [45]:
df[["rollNo","name"]]

   rollNo    name
0       1    amit
1       2  suresh
2       3    yash
3       4    neha
4       5    aman

In [46]:
df

   rollNo    name  marks
0       1    amit    100
1       2  suresh     90
2       3    yash     60
3       4    neha     70
4       5    aman     40

In [47]:
#find the students who score more than 80
df[df["marks"]>80]

   rollNo    name  marks
0       1    amit    100
1       2  suresh     90

In [51]:
df[(df["marks"]>=50) & (df["marks"]<=70)][['rollNo','name']]

   rollNo  name
2       3  yash
3       4  neha